SELECT CREW.NAME,CAST_.GENDER
FROM CREW
INNER JOIN CAST_ ON CAST_.C_ID = CREW.C_ID 
WHERE CREW.C_ID IN (SELECT C_ID
					FROM PART_OF_M
					WHERE M_ID IN (SELECT M_ID
									FROM BELONGS_TO_M
									WHERE NAME = 'Drama'));